### ISSUE TITLE
Inconsitency between Python version in docs and pyproject.toml

### ISSUE THREAD

**Issue by AllanLeanderRostockHansen** [jaysnm/dremio-arrow#15]
The pyproject.toml says one thing
https://github.com/jaysnm/dremio-arrow/blob/cebb6f32cb0c58d95bd995b50a4b5cda45e65c79/pyproject.toml#L24

Docs says 3.7 to 3.10:
https://jaysnm.github.io/dremio-arrow/installation/

**Comment by jaysnm** [comment]
Hello @AllanLeanderRostockHansen 

Thanks for pointing out. I updated the package and forgot to update docs. Technically the package should work for all python versions >= 3.7 as the actual change wasn't effected on the code. Would be great if you can make a PR (a star is also a great way of showing support).

There are a couple of action points on the Discussions tab that I couldn't get into but hope to be back there soon. Any help is much appreciated in advance.

**Comment by AllanLeanderRostockHansen** [comment]
Sorry for the late reply, please review this PR: https://github.com/jaysnm/dremio-arrow/pull/20

I hope you will go through the hassle of releasing this on Pypi if the PR is merged, as that would greatly ease how we can integrate this project in our CI/CD builds 😄

**Comment by jaysnm** [comment]
Dear Allan,

Thank you for your time and effort in improving the package. I have merged the PR and preparing a patched release to PYPI. Once again, many thanks.
