### ISSUE TITLE
Any plans to support conda packages

### ISSUE THREAD

**Issue by rxm7706** [jaysnm/dremio-arrow#2]
* dremio-arrow version: 1.0.1
* Python version: 3.7
* Operating System: Linux

### Description

Do you intend to support a conda packaged version on conda-forge

**Comment by jaysnm** [comment]
I have no plans for this. Open for PR!

**Comment by rxm7706** [comment]
@jaysnm https://anaconda.org/conda-forge/dremio-arrow
conda install -c conda-forge dremio-arrow
Also thank you, for this developing, maintaining and sharing dremio-arrow
