### ISSUE TITLE
Upgrade to Support PyArrow 9.0.0

### ISSUE THREAD

**Issue by rxm7706** [jaysnm/dremio-arrow#3]
dremio-arrow version: 1.0.1
    Python version: 3.7
    Operating System: Linux

Description

Latest Dremio version ships with Pyarrow 9.0.0, so far everything in arrow and flight works well with arrow 9.0.0

Any reason to not change the pins from <8.0 to <10..0 allowing installtion without downgrading existing environments from pyarrow 9.0 to 8.0

**Comment by jaysnm** [comment]
Hello. Thank you for trying out the package. 
There is absolutely no reason for not upgrading to latest pyarrow. If you have done any work on this please share a PR.

**Comment by rxm7706** [comment]
@elanqo @cshaley could you take a look please.

**Comment by rxm7706** [comment]
@jaysnm - Excited to hear you are looking to actively maintain dremio-arrow. 
@elanqo has raised a PR and @cshaley and me will be glad to help too. https://github.com/jaysnm/dremio-arrow/pull/6
It would be very helpful if you can think about adding additional maintainers - so that we can contribute too.

**Comment by jaysnm** [comment]
Hello @rxm7706 

Thank you for being an active user of dremio-arrow package. I have reviewed Emannuels's PR and left a comment. I would be more than happy to have more persons maintaining this package. Let's discuss maintenance issues on #5.

Thanks

**Comment by jaysnm** [comment]
Dear @rxm7706 

The package now supports latest pandas (2.0.3) and latest pyarrow (12.0.1).  Thank you for active participation. Feel free to add your other opinions on how you would wish to see this package grow on issue #5
